export const EMAIL_CHANGES = 'EMAIL_CHANGES';
export const PASSWORD_CHANGES = 'PASSWORD_CHANGES';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
